/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teste4banco;

/**
 *
 * @author ramon
 */
public class JanelaProduto extends javax.swing.JDialog {

    /**
     * Creates new form JanelaProduto
     */
    public JanelaProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(760, 408));
        setMinimumSize(new java.awt.Dimension(760, 408));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 128, 0));
        jPanel1.add(jPanel2);
        jPanel2.setBounds(-50, 200, 410, 210);

        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Status:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 380, 300, 20);

        jButton2.setBackground(new java.awt.Color(0, 153, 255));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Incluir");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(420, 240, 310, 40);

        jButton1.setBackground(new java.awt.Color(255, 153, 0));
        jButton1.setForeground(new java.awt.Color(1, 1, 1));
        jButton1.setText("Buscar");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 190, 310, 40);

        jButton3.setBackground(new java.awt.Color(102, 255, 102));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Alterar");
        jButton3.setBorderPainted(false);
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(420, 290, 310, 40);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("X");
        jButton5.setBorder(null);
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(720, 0, 40, 40);

        jButton4.setBackground(new java.awt.Color(255, 51, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Excluir");
        jButton4.setBorderPainted(false);
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(420, 340, 310, 32);

        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Código:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(420, 30, 42, 16);

        jTextField1.setForeground(new java.awt.Color(1, 1, 1));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(420, 50, 310, 24);

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 80, 36, 16);

        jTextField2.setForeground(new java.awt.Color(1, 1, 1));
        jPanel1.add(jTextField2);
        jTextField2.setBounds(420, 100, 310, 24);

        jPanel3.setBackground(new java.awt.Color(255, 128, 0));
        jPanel1.add(jPanel3);
        jPanel3.setBounds(720, -20, 80, 60);

        jPanel4.setBackground(new java.awt.Color(255, 112, 0));
        jPanel1.add(jPanel4);
        jPanel4.setBounds(280, 160, 110, 90);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("WOW Solutions for TI.");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 130, 370, 90);

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("Unidade:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(420, 130, 60, 16);

        jTextField3.setForeground(new java.awt.Color(1, 1, 1));
        jPanel1.add(jTextField3);
        jTextField3.setBounds(420, 150, 310, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 760, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        int cod = Integer.parseInt(jTextField1.getText());
        String nome = jTextField2.getText().trim();
        Double precoUnit = Double.parseDouble( jTextField3.getText()); 
                
        ControleProduto cv = new ControleProduto();
        Produto v = cv.inserirPorCodigo(cod,nome,precoUnit);

        if (v != null) {
            jTextField2.setText(v.getNome());
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
        } else {
            jLabel3.setText("Status: Erro ao inserir...");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int cod = Integer.parseInt(jTextField1.getText());
        ControleProduto cv = new ControleProduto();
        Produto v = cv.buscarPorCodigo(cod);
        if (v != null) {
            jTextField2.setText(v.getNome());
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
        } else {
            jLabel3.setText("Status: Código não encontrado...");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        int cod = Integer.parseInt(jTextField1.getText());
        String nome = jTextField2.getText().trim();
        Double precoUnit = Double.parseDouble( jTextField3.getText()); 
        
        ControleProduto cv = new ControleProduto();
        Produto v = cv.alterarPorCodigo(cod,nome,precoUnit);

        if (v != null) {
            jTextField2.setText(v.getNome());
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
        } else {
            jLabel3.setText("Status: Erro na alteração...");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int cod = Integer.parseInt(jTextField1.getText());
        ControleProduto cv = new ControleProduto();
        Produto v = cv.excluirPorCodigo(cod);
        if (v != null) {
            jTextField2.setText(v.getNome());
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
        } else {
            jLabel3.setText("Status: Não foi possível excluir...");
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JanelaProduto dialog = new JanelaProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
